version: '3.8'

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/etc/prometheus/rules
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /etc/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - "9093:9093"


  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${VAULT_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: monitoring_db
      MYSQL_USER: ${VAULT_MYSQL_USER}
      MYSQL_PASSWORD: ${VAULT_MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - monitoring

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql_exporter
    environment:
      DATA_SOURCE_NAME: "${VAULT_MYSQL_USER}:${VAULT_MYSQL_PASSWORD}@(mysql:3306)/"
    ports:
      - "9104:9104"
    networks:
      - monitoring

  # --- LOGGING ---
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
