{
 "title": "Loki Dashboard",
 "description": "Loki dashboard with quick search and timeline.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "search" },
   { "name": "DS_LOKI", "query": "loki" },
   {
    "name": "job",
    "query": {}
   },
   {
    "name": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Timeline",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (host) (count_over_time({host=\"$host\", job=~\"$job\"} |= \"$search\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Danh sách các IP bị chặn gần nhất",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/log/fail2ban.log\", host=\"$host\"} | regexp \".*Ban (?P<ip_address>\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3})\""
    }
   ]
  },
  {
   "title": "Tổng IP bị chặn (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({filename=\"/var/log/fail2ban.log\", host=\"$host\"} |= \"Ban\" [24h])"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"$host\", job=~\"$job\"} |= \"$search\""
    }
   ]
  }
 ]
}