global:
  resolve_timeout: 30s

route:
  receiver: 'telegram-bot'
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 1m

receivers:
- name: 'telegram-bot'
  telegram_configs:
  - bot_token: "{{ vault_telegram_token }}"
    chat_id: {{ vault_telegram_chat_id }}
