global:
  resolve_timeout: 5m

route:
  receiver: 'telegram-bot'

receivers:
- name: 'telegram-bot'
  telegram_configs:
  - bot_token: "{{ vault_telegram_token }}"
    chat_id: {{ vault_telegram_chat_id }}
