- hosts: nodes
  become: yes

  roles:
    - common
    - maintenance

- hosts: monitoring
  become: yes
  vars_files:
    - "../group_vars/all/vault.yml"
  tasks:
    - name: Tạo thư mục cấu hình Alertmanager trên server
      file:
        path: /etc/alertmanager
        state: directory
        mode: '0755'

    - name: Copy và giải mã file cấu hình Alertmanager
      template:
        src: alertmanager/alertmanager.yml
        dest: /etc/alertmanager/alertmanager.yml
        mode: '0644'
